### ISSUE TITLE
Question: How can I edit toggleads.cfg to make it work for holding ADS?

### ISSUE THREAD

**Issue by jdkennedy45** [NotTsunami/ApexConfig#1]

**Comment by NotTsunami** [comment]
For some reason I didn't get any notification for this, my apologies for the delayed response. To clear up a lot of confusion over binds I've removed the script in the latest version. It's a cool concept but the crowd that it's aimed at likely doesn't overlap with many of my users.

I would recommend removing it, launching and resetting binds, and then in Settings->Controls there should be a bind option for both "Aim (Hold)" and "Aim (Toggle)", set your right mouse button to whichever you would prefer.
